### PR TITLE
Fix compatibility with webpack 5

### LINKED ISSUE #668: Plugin crashes when using in a repo with webpack 4 and webpack 5
- Operating System: macOS 10.15.7
- Node Version: v15.3.0
- Yarn Version: 1.22.4
- webpack Version: 4.44.2 **and** 5.10.3
- mini-css-extract-plugin Version: 1.3.3

### Expected Behavior

It can bundle my app without crashing.

### Actual Behavior

Crashes with:

```
$ webpack
[webpack-cli] TypeError: Cannot read property 'ensureChunkHandlers' of undefined
    at /Users/sergio/src/test/mini-css-extract-plugin-bug/node_modules/mini-css-extract-plugin/dist/index.js:322:88
    at Hook.eval [as call] (eval at create (/Users/sergio/src/test/mini-css-extract-plugin-bug/app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/sergio/src/test/mini-css-extract-plugin-bug/app/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/sergio/src/test/mini-css-extract-plugin-bug/app/node_modules/webpack/lib/Compiler.js:987:30)
    at /Users/sergio/src/test/mini-css-extract-plugin-bug/app/node_modules/webpack/lib/Compiler.js:1029:29
    at Hook.eval [as callAsync] (eval at create (/Users/sergio/src/test/mini-css-extract-plugin-bug/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/sergio/src/test/mini-css-extract-plugin-bug/app/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/sergio/src/test/mini-css-extract-plugin-bug/app/node_modules/webpack/lib/Compiler.js:1024:28)
    at /Users/sergio/src/test/mini-css-extract-plugin-bug/app/node_modules/webpack/lib/Compiler.js:471:12
    at Compiler.readRecords (/Users/sergio/src/test/mini-css-extract-plugin-bug/app/node_modules/webpack/lib/Compiler.js:866:11)
```

### How Do We Reproduce?

See reproduction repo in https://github.com/scinos/mini-css-extract-plugin-bug

### Description

This is what I think it is happening:

In a monorepo with multiple versions of webpack, depending on where `mini-css-extract-plugin` physically is, it can fail. Example:

```
// Package structure
<root>
    node_modules/
        webpack@4.44.2
        mini-css-extract-plugin@1.3.3.
    app/
        node_modules/
            webpack@5.10.0
```

Note that both `<root>` and `app` depend on `mini-css-extract-plugin@1.3.3.`, but the package manager hoists it to a common location. Because how the node module resolution algorithm works, this setup is valid (and in fact, quite common for monorepos).

Now imagine a webpack compilation inside `app` that uses `new MiniCssExtractPlugin()` (details about what the config does are not relevant). This is what happens:

- A new webpack 5 compilation is started, it loads `MiniCssExtractPlugin`
- The plugin imports `import webpack from 'webpack';` (https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L3). As the plugin resides in `<root>/node_modules/mini-css-extract-plugin`, it loads `<root>/node_modules/webpack` which is **webpack 4**
- Later, the plugin checks if the `compiler` was created using webpack 4 (https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L106). It wasn't, so it assumes **webpack 5.**
- Later the plugin does the equivalent of (edited for example, code in https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L486):
    ```
    if (!isWebpack4) {
       doStuff(webpack.RuntimeGlobals.ensureChunkHandlers)
    }
    ```
- Crashes because `isWebpack4===false`, but `webpack` does point to `wepback@4.44.2`

image

### PR DESCRIPTION
**Pull request by alexander-akait**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

use `compiler.webpack` for better compatibility with webpack v5

fixes #668

### Breaking Changes

No

### Additional Info

No

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -27,69 +12,289 @@ const REGEXP_CONTENTHASH = /\[contenthash(?::(\d+))?\]/i;
...
-  const pathLength = `${pluginName}/dist`.length;
+const TYPES = new Set([MODULE_TYPE]);
+const CODE_GENERATION_RESULT = {
+  sources: new Map(),
+  runtimeRequirements: new Set(),
+};
+
+class MiniCssExtractPlugin {
+  static getCssModule(webpack) {
+    class CssModule extends webpack.Module {
```
Comment (abearxiong) [inline src/index.js:23]: image

why i will get undefined;

    "webpack": "5.15.0",
    "webpack-build-notifier": "^2.1.1",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^3.11.2",
    "webpack-merge": "^5.7.3"

Comment (alexander-akait) [reply src/index.js:23]: Please create reproducible test repo

**Comment by taejs** [comment]
Hi. I think this commit cause this error. 
https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/167
